# Site settings
title: jopemachine. dev blog
SEOTitle: jopemachine. dev blog
header-img: img/home-bg.jpg
email: jopemachine@naver.com
# description: "Aim to share my study and my thoughts about all kinds of personal development experience"
description: "개발 관련 개인적인 일상, 후기, 생각, 스터디, 문서 번역 등 각종 포스팅을 정리하고 공부하고, 공유합니다."
keyword: "frontend, jopemachine, gyubong, gyubong lee, react, javascript"
url: "https://jopemachine.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     jopemachine
#zhihu_username:     jopemachine
github_username:    jopemachine
#twitter_username:   jopemachine
#facebook_username:  jopemachine
linkedin_username:  gyu-bong-lee-a1a76b197

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: jopemachine
duoshuo_share: false

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: jopemachine.me

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "다양한 CS 분야에 관심을 갖고 공부하는 주니어 개발자입니다."
sidebar-avatar: /img/profile.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#ffffff"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# jekyll-tipue-search
tipue_search:
  include:
    pages: false
    collections: []
  exclude:
      files: [index.html]
      categories: []
      tags: []

# Friends
# friends: [
#     {
#         title: "Haru",
#         href: "https://toitoitoi79.tistory.com/"
#     },
# ]
